
/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
 * the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * Find the sum of all the even-valued terms in the sequence which do not exceed four million.
 * Note: This problem has been changed recently, please check that you are using the right parameters. 
 * */

public class Prob2 {

	
	public static void main(String[] args) {
		
		int[] fib = new int[35];
		int sum = 2;
		int x = 2;
		int jako;
		fib[0] = 1;
		fib[1] = 2;
		
		for (; x <= 34; x++) {
			fib[x] = fib[x-1] + fib[x-2];
			if ((fib[x]) <= 4000000) {
				jako = (fib[x] % 2);
				if (jako  == 0) {
					System.out.println("Index: "+x+" Value: "+fib[x]);
					sum += fib[x];
				}

			}
		}
		System.out.println("Here's the sum: "+sum);

	}

}
